### ISSUE TITLE
Remove AbleCop from this repository

### ISSUE THREAD

**Issue by mpotter** [ableco/gems.able.co#10]
@dennmart should we remove AbleCop from this repo since we deprecated with https://github.com/ableco/ablecop, right?

**Comment by dennmart** [comment]
@mpotter Yep! I'm waiting to merge in the last pull request I have for AbleCop so that I can point the projects that are using the gem (Core and PICI) to the new repo in their Gemfiles. Then I'll have a pull request to remove AbleCop here.
